AWSTemplateFormatVersion: '2010-09-09'
Transform: "AWS::Serverless-2016-10-31"
Description: 'Amazon Elasticsearch Service with Amazon Cognito'

Metadata:
  AWS::ServerlessRepo::Application:
    Name: amazon-elasticsearch-cognito-auth
    Description: >
      Amazon Elasticsearch Service with Amazon Cognito
    Author: Kazuki Matsuda
    SpdxLicenseId: Apache-2.0
    LicenseUrl: LICENSE
    ReadmeUrl: README.md
    Labels: ['elasticsearch', 'cognito']
    HomepageUrl: https://github.com/mats16/amazon-elasticsearch-cognito-auth/tree/master/cognito
    SemanticVersion: 0.3.0
    SourceCodeUrl: https://github.com/mats16/amazon-elasticsearch-cognito-auth/tree/master/cognito
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Elasticsearch Configuration
        Parameters:
          - ElasticsearchVersion
          - ElasticsearchAvailabilityZoneCount
          - ElasticsearchInstanceType
          - ElasticsearchInstanceCount
          - ElasticsearchMasterType
          - ElasticsearchMasterCount
      - Label:
          default: Cognito Configuration
        Parameters:
          - CognitoAllowedEmailDomains

Globals:
  Function:
    Timeout: 5

Parameters:
  ElasticsearchVersion:
    Description: 7.x supported only
    Type: String
    Default: 7.4
    AllowedPattern: ^7\.[0-9]+$
  ElasticsearchAvailabilityZoneCount:
    Type: Number
    Default: 2
    AllowedValues:
      - 1
      - 2
      - 3
  ElasticsearchInstanceType:
    Description: i3 family supported only
    Type: String
    Default: i3.large.elasticsearch
    AllowedPattern: ^[a-z1-9]+\.[a-z1-9]+\.elasticsearch$
  ElasticsearchInstanceCount:
    Type: Number
    Default: 2
  ElasticsearchMasterType:
    Type: String
    Default: t2.medium.elasticsearch
    AllowedPattern: ^[a-z1-9]+\.[a-z1-9]+\.elasticsearch$
  ElasticsearchMasterCount:
    Type: Number
    Default: 3
  CognitoAllowedEmailDomains:
    Type: CommaDelimitedList
    Description: Specific domains allowed to register on Cognito
    Default: amazon.com,amazon.co.jp
  ReaderRoleEnabled:
    Type: String
    Default: false
    AllowedValues:
      - false
      - true

Conditions:
  EBSDisabled: !Or
    - !Equals [!Ref ElasticsearchInstanceType, 'i3.large.elasticsearch']
    - !Equals [!Ref ElasticsearchInstanceType, 'i3.xlarge.elasticsearch']
    - !Equals [!Ref ElasticsearchInstanceType, 'i3.2xlarge.elasticsearch']
    - !Equals [!Ref ElasticsearchInstanceType, 'i3.4xlarge.elasticsearch']
    - !Equals [!Ref ElasticsearchInstanceType, 'i3.8xlarge.elasticsearch']
    - !Equals [!Ref ElasticsearchInstanceType, 'i3.16xlarge.elasticsearch']
  ReaderRoleEnabled: !Equals [!Ref ReaderRoleEnabled, 'true']

Resources:

  Elasticsearch:
    Type: AWS::Elasticsearch::Domain
    DependsOn: UserPoolDomain
    DeletionPolicy: Retain
    Properties:
      ElasticsearchVersion: !Ref ElasticsearchVersion
      ElasticsearchClusterConfig:
        ZoneAwarenessEnabled: true
        ZoneAwarenessConfig:
           AvailabilityZoneCount: !Ref ElasticsearchAvailabilityZoneCount
        InstanceType: !Ref ElasticsearchInstanceType
        InstanceCount: !Ref ElasticsearchInstanceCount
        DedicatedMasterEnabled: true
        DedicatedMasterType: !Ref ElasticsearchMasterType
        DedicatedMasterCount: !Ref ElasticsearchMasterCount
      EBSOptions:
        EBSEnabled: !If [EBSDisabled, !Ref AWS::NoValue, true]
        VolumeSize: !If [EBSDisabled, !Ref AWS::NoValue, 100]
      CognitoOptions:
        Enabled: true
        UserPoolId: !Ref KibanaUserPool
        IdentityPoolId: !Ref KibanaIdentityPool
        RoleArn: !GetAtt CognitoAccessForAmazonES.Arn
      AdvancedOptions:
        rest.action.multi.allow_explicit_index: true
      AccessPolicies: !Sub |
        {
          "Version": "2012-10-17",
          "Statement": [
            {
              "Effect": "Allow",
              "Principal": {
                "AWS": [
                  "${AWS::AccountId}"
                ]
              },
              "Action": [
                "es:*"
              ],
              "Resource": "arn:aws:es:${AWS::Region}:${AWS::AccountId}:domain/*/*"
            }
          ]
        }

  CognitoAccessForAmazonES:
    Type: AWS::IAM::Role
    Properties:
      Description: 'Amazon Elasticsearch role for Kibana authentication.'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: es.amazonaws.com
            Action: 'sts:AssumeRole'
      ManagedPolicyArns: 
        - arn:aws:iam::aws:policy/AmazonESCognitoAccess
      Path: /service-role/

  PreSignUp:
    Type: AWS::Serverless::Function
    Properties:
      Description: 'Validate e-mail domain just before sign-up'
      CodeUri: cognito-pre-sign-up/
      Handler: index.lambda_handler
      Runtime: python3.6
      Environment:
        Variables:
          ALLOWED_DOMAINS: !Join [',', !Ref CognitoAllowedEmailDomains] 

  PreSignUpInvocationPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt PreSignUp.Arn
      Principal: cognito-idp.amazonaws.com
      SourceArn: !GetAtt KibanaUserPool.Arn

  KibanaUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UsernameAttributes:
        - email
      AutoVerifiedAttributes:
        - email
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: true
          RequireUppercase: true
      Schema:
        - Name: email
          AttributeDataType: String
          DeveloperOnlyAttribute: false
          Mutable: true
          Required: true
      LambdaConfig:
        PreSignUp: !GetAtt PreSignUp.Arn

  KibanaIdentityPool:
    Type: AWS::Cognito::IdentityPool
    Properties:
      AllowUnauthenticatedIdentities: true

  KibanaAuthorRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action: "sts:AssumeRoleWithWebIdentity"
            Principal:
              Federated: cognito-identity.amazonaws.com
            Condition:
              StringEquals:
                "cognito-identity.amazonaws.com:aud": !Ref KibanaIdentityPool
              ForAnyValue:StringLike:
                "cognito-identity.amazonaws.com:amr": authenticated
      Policies:
        - PolicyName: AuthorPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - 'es:ESHttp*'
                Resource:
                  - !Sub '${Elasticsearch.Arn}/*'

  KibanaReaderRole:
    Type: AWS::IAM::Role
    Condition: ReaderRoleEnabled
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action: "sts:AssumeRoleWithWebIdentity"
            Principal:
              Federated: cognito-identity.amazonaws.com
            Condition:
              StringEquals:
                "cognito-identity.amazonaws.com:aud": !Ref KibanaIdentityPool
              ForAnyValue:StringLike:
                "cognito-identity.amazonaws.com:amr": authenticated
      Policies:
        - PolicyName: ReaderPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - 'es:ESHttpHead'
                  - 'es:ESHttpGet'
                  - 'es:ESHttpPost'
                Resource:
                  - !Sub '${Elasticsearch.Arn}/*'

  RoleAttachment:
    Type: AWS::Cognito::IdentityPoolRoleAttachment
    Properties:
      IdentityPoolId: !Ref KibanaIdentityPool
      Roles:
        authenticated: !If [ReaderRoleEnabled, !GetAtt KibanaReaderRole.Arn, !GetAtt KibanaAuthorRole.Arn]
      #RoleMappings:
      #  userpool1:
      #    IdentityProvider: !Ref KibanaUserPool
      #    AmbiguousRoleResolution: AuthenticatedRole
      #    Type: Token

  Authors:
    Type: AWS::Cognito::UserPoolGroup
    Condition: ReaderRoleEnabled
    Properties: 
      Description: Create and publish interactive dashboards
      GroupName: Authors
      Precedence: 0
      RoleArn: !GetAtt KibanaAuthorRole.Arn
      UserPoolId: !Ref KibanaUserPool

  UserPoolDomain:
    Type: Custom::UserPoolDomain
    Version: 1.0
    Properties:
      ServiceToken: !GetAtt ModifyUserPoolDomain.Arn
      UserPoolId: !Ref KibanaUserPool

  ModifyUserPoolDomain:
    Type: AWS::Serverless::Function
    Properties:
      Description: '[CFn Custom Resource] modify a domain prefix for the sign-in page hosted by Amazon Cognito'
      CodeUri: custom_resources/userpool_domain/
      Handler: index.lambda_handler
      Runtime: python3.6
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: "Allow"
              Action:
                - "cognito-idp:CreateUserPoolDomain"
                - "cognito-idp:DeleteUserPoolDomain"
              Resource:
                - !GetAtt KibanaUserPool.Arn

  ModifyTemplate:
    Type: AWS::Serverless::Function
    Properties:
      Description: '[CFn Custom Resource] modify a mapping template of Amazon Elasticsearch Service'
      CodeUri: custom_resources/elasticsearch_template/
      Handler: index.lambda_handler
      Runtime: python3.6
      Environment:
        Variables:
          ES_HOST: !GetAtt Elasticsearch.DomainEndpoint
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - es:ESHttpPut
                - es:ESHttpDelete
              Resource:
                - !Sub 'arn:aws:es:${AWS::Region}:${AWS::AccountId}:domain/*/_template/*'

Outputs:

  Arn:
    Value: !GetAtt Elasticsearch.Arn

  Endpoint:
    Value: !GetAtt Elasticsearch.DomainEndpoint

  ModifyTemplateArn:
    Value: !GetAtt ModifyTemplate.Arn
